server:
  port: 2040
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost.5432/estoutic
    driver-class-name: org.postgresql.Driver
    username: admin@mail.ru
    password: admin
  jpa:
    database-platform: org,hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop


